name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 2.0.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Static Analysis
        run: |
          nimble check -Y

      - name: Test
        run: |
          nimble test

      - name: Local Install
        run: |
          nimble develop -g

      - name: '[unix] Examples'
        if: ${{ !startsWith(matrix.os, 'windows') }}
        working-directory: examples
        run: |
          for example in $(ls); do
            pushd ${example}

            nimble setup -Y
            nimble exo_build
            nimble exo_debug

            popd
          done

      - name: '[windows] Examples'
        if: startsWith(matrix.os, 'windows')
        working-directory: examples
        run: |
          $examples = Get-ChildItem .
          foreach ($example in $examples) {
            cd $example

            nimble setup -Y
            nimble exo_build
            nimble exo_debug

            cd ..
          }
