name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 2.0.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Static Analysis
        run: |
          nimble check -Y

      - name: Build Examples
        run: |
          nimble install

          cd examples/hello
          nimble setup -Y
          nimble build_hello
